export const GET_CURRENT_CARD = 'GET_CURRENT_CARD';
export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const SET_CURRENT_CARD = 'SET_CURRENT_CARD';
export const SET_ENDOWMENT_TIME = 'SET_ENDOWMENT_TIME';
export const CLEAR_COUNT = 'CLEAR_COUNT';
export const CHECK = 'CHECK';
export const FLOW_TURN = 'FLOW_TURN';
export const END_ENDOWMENT = 'END_ENDOWMENT';
export const ROUND = 'ROUND';

export default {
  GET_CURRENT_CARD,
  SET_CURRENT_CARD,
  SET_ENDOWMENT_TIME,
  INCREASE,
  DECREASE,
  CLEAR_COUNT,
  CHECK,
  FLOW_TURN,
  END_ENDOWMENT,
  ROUND,
};
